_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": AUC
              "6":
                - 3
              "7":
                - 3
            - "1": C-index
              "6":
                - 3
              "7":
                - 3
            - "1": IBS
              "6":
                - 3
              "7":
                - 3
            - "1": MAE_Hinge
              "6":
                - 3
              "7":
                - 3
            - "1": MAE_PO
              "6":
                - 3
              "7":
                - 3
            - "1": KM-cal
              "6":
                - 3
              "7":
                - 3
            - "1": D-cal
              "6":
                - 3
              "7":
                - 3
            - "1": BS
              "6":
                - 3
              "7":
                - 3
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 23
                - 55
                - 63
            "4": 3.12.1
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
activation:
    value: ReLU
batch_size:
    value: 256
device:
    value: cpu
dropout:
    value: 0.4
early_stop:
    value: false
lr:
    value: 1
model:
    value: CoxPH
n_epochs:
    value: 5
n_exp:
    value: 1
n_features:
    value: 10
neurons:
    value: []
norm:
    value: true
seed:
    value: 0
timestamp:
    value: "20250704_131446"
verbose:
    value: true
weight_decay:
    value: 0.001
